// Code generated by MockGen. DO NOT EDIT.
// Source: yadro.com/course/search/core (interfaces: Initiator)
//
// Generated by this command:
//
//	mockgen -destination=mock_initiator_test.go -package=core . Initiator
//

// Package core is a generated GoMock package.
package core

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInitiator is a mock of Initiator interface.
type MockInitiator struct {
	ctrl     *gomock.Controller
	recorder *MockInitiatorMockRecorder
	isgomock struct{}
}

// MockInitiatorMockRecorder is the mock recorder for MockInitiator.
type MockInitiatorMockRecorder struct {
	mock *MockInitiator
}

// NewMockInitiator creates a new mock instance.
func NewMockInitiator(ctrl *gomock.Controller) *MockInitiator {
	mock := &MockInitiator{ctrl: ctrl}
	mock.recorder = &MockInitiatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInitiator) EXPECT() *MockInitiatorMockRecorder {
	return m.recorder
}

// BuildIndex mocks base method.
func (m *MockInitiator) BuildIndex(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildIndex", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildIndex indicates an expected call of BuildIndex.
func (mr *MockInitiatorMockRecorder) BuildIndex(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildIndex", reflect.TypeOf((*MockInitiator)(nil).BuildIndex), arg0)
}
