// Code generated by MockGen. DO NOT EDIT.
// Source: yadro.com/course/search/core (interfaces: Searcher)
//
// Generated by this command:
//
//	mockgen -destination=mock_searcher.go -package=core . Searcher
//

// Package core is a generated GoMock package.
package core

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearcher is a mock of Searcher interface.
type MockSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockSearcherMockRecorder
	isgomock struct{}
}

// MockSearcherMockRecorder is the mock recorder for MockSearcher.
type MockSearcherMockRecorder struct {
	mock *MockSearcher
}

// NewMockSearcher creates a new mock instance.
func NewMockSearcher(ctrl *gomock.Controller) *MockSearcher {
	mock := &MockSearcher{ctrl: ctrl}
	mock.recorder = &MockSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearcher) EXPECT() *MockSearcherMockRecorder {
	return m.recorder
}

// ISearch mocks base method.
func (m *MockSearcher) ISearch(arg0 context.Context, arg1 string, arg2 int) ([]Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ISearch", arg0, arg1, arg2)
	ret0, _ := ret[0].([]Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ISearch indicates an expected call of ISearch.
func (mr *MockSearcherMockRecorder) ISearch(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ISearch", reflect.TypeOf((*MockSearcher)(nil).ISearch), arg0, arg1, arg2)
}

// Search mocks base method.
func (m *MockSearcher) Search(arg0 context.Context, arg1 string, arg2 int) ([]Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1, arg2)
	ret0, _ := ret[0].([]Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearcherMockRecorder) Search(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearcher)(nil).Search), arg0, arg1, arg2)
}
